/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-25 03:20:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<!-- location_area -->\r\n");
      out.write("		<div class=\"location_area member\">\r\n");
      out.write("			<div class=\"box_inner\">\r\n");
      out.write("				<h2 class=\"tit_page\">TOURIST <span class=\"in\">in</span> TOUR</h2>\r\n");
      out.write("				<p class=\"location\">MEMBER <span class=\"path\">/</span> 회원가입</p>\r\n");
      out.write("				<ul class=\"page_menu clear\">\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"on\">회원가입</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- //location_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- bodytext_area -->\r\n");
      out.write("		<div class=\"bodytext_area box_inner\">\r\n");
      out.write("			<!-- appForm -->\r\n");
      out.write("			<form action=\"#\" class=\"appForm\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>상담문의 입력 양식</legend>\r\n");
      out.write("					<p class=\"info_pilsoo pilsoo_item\">필수입력</p>\r\n");
      out.write("					<ul class=\"app_list\">\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("                            <label for=\"email_lbl\" class=\"tit_lbl pilsoo_item\">이메일</label>\r\n");
      out.write("                            <div class=\"app_content email_area\">\r\n");
      out.write("                                <input type=\"text\" class=\"w160\" id=\"email_lbl\" title=\"이메일 주소\" />\r\n");
      out.write("                                <span class=\"ico_space\">@</span>\r\n");
      out.write("                                <input type=\"text\" class=\"w160\" title=\"이메일 제공업체 입력\" />										\r\n");
      out.write("                                <div class=\"select_common\">\r\n");
      out.write("                                    <select title=\"이메일 제공업체 목록\">\r\n");
      out.write("                                        <option value=\"\">직접입력</option>\r\n");
      out.write("                                        <option value=\"\">naver.com</option>\r\n");
      out.write("                                        <option value=\"\">hanmail.net</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>										\r\n");
      out.write("                            </div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"name_lbl\" class=\"tit_lbl pilsoo_item\">작성자명</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"text\" class=\"w100p\" id=\"name_lbl\" placeholder=\"이름을 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"pwd_lbl\" class=\"tit_lbl pilsoo_item\">비밀번호</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"password\" class=\"w100p\" id=\"pwd_lbl\" placeholder=\"비밀번호를 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"pwd2_lbl\" class=\"tit_lbl pilsoo_item\">비밀번호 확인</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"password\" class=\"w100p\" id=\"pwd2_lbl\" placeholder=\"비밀번호를 다시 한번 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"phone_lbl\" class=\"tit_lbl pilsoo_item\">연락처</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"tel\" class=\"w100p\" id=\"phone_lbl\" placeholder=\"휴대폰”-”없이 숫자만 입력하세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<span class=\"tit_lbl\">성별</span>\r\n");
      out.write("							<div class=\"app_content radio_area\">\r\n");
      out.write("								<input type=\"radio\" class=\"css-radio\" id=\"mmm_lbl\" name=\"gender\"><label for=\"mmm_lbl\">남</label>\r\n");
      out.write("								<input type=\"radio\" class=\"css-radio\" id=\"www_lbl\" name=\"gender\"><label for=\"www_lbl\">여</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("                            <span class=\"tit_lbl\">SNS 수신동의</span>\r\n");
      out.write("							<div class=\"app_content checkbox_area\">\r\n");
      out.write("								<input type=\"checkbox\" class=\"css-checkbox\" id=\"agree_lbl\" name=\"agree1\"><label for=\"agree_lbl\">동의함</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("                            <span class=\"tit_lbl\">이메일 수신동의</span>\r\n");
      out.write("							<div class=\"app_content checkbox_area\">\r\n");
      out.write("								<input type=\"checkbox\" class=\"css-checkbox\" id=\"agree_lb2\" name=\"agree2\"><label for=\"agree_lb2\">동의함</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"content_lbl\" class=\"tit_lbl\">문의내용</label>\r\n");
      out.write("							<div class=\"app_content\"><textarea id=\"content_lbl\" class=\"w100p\" placeholder=\"간단한 상담 요청 사항을 남겨주시면 보다 상세한 상담이 가능합니다.\r\n");
      out.write("전화 상담 희망시 기재 부탁드립니다.\"></textarea></div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p class=\"btn_line\"><a href=\"javascript:;\" class=\"btn_baseColor\">등록</a></p>	\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("			<!-- //appForm -->\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //bodytext_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //container -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
