/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-25 03:20:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<!-- location_area -->\r\n");
      out.write("		<div class=\"location_area member\">\r\n");
      out.write("			<div class=\"box_inner\">\r\n");
      out.write("				<h2 class=\"tit_page\">TOURIST <span class=\"in\">in</span> TOUR</h2>\r\n");
      out.write("				<p class=\"location\">MYPAGE <span class=\"path\">/</span> 개인 정보 수정</p>\r\n");
      out.write("				<ul class=\"page_menu clear\">\r\n");
      out.write("					<li><a href=\"#\" class=\"on\">개인 정보 수정</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- //location_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- bodytext_area -->\r\n");
      out.write("		<div class=\"bodytext_area box_inner\">\r\n");
      out.write("			<!-- myinfo -->\r\n");
      out.write("			<dl class=\"myinfo\">\r\n");
      out.write("				<dt>내 정보</dt>\r\n");
      out.write("				<dd>\r\n");
      out.write("					<!-- appForm -->\r\n");
      out.write("					<form action=\"#\" class=\"regForm\">\r\n");
      out.write("						<fieldset>\r\n");
      out.write("							<legend>내정보 입력 양식</legend>\r\n");
      out.write("							<ul class=\"reg_list\">\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">이름</span>\r\n");
      out.write("									<div class=\"reg_content\">홍길동</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<label class=\"tit_lbl\">생년월일</label>\r\n");
      out.write("									<div class=\"reg_content\">19910327</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">성별</span>\r\n");
      out.write("									<div class=\"reg_content radio_area\">\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"mmm_lbl\" name=\"gender\" checked><label for=\"mmm_lbl\">남</label>\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"www_lbl\" name=\"gender\"><label for=\"www_lbl\">여</label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">주소</span>\r\n");
      out.write("									<div class=\"reg_content\">서울시 종로구 인사동 111-35 오리엔트파빌리온 1024호</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">핸드폰</span>\r\n");
      out.write("									<div class=\"reg_content\">010-1234-1234</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">SMS 수신동의</span>\r\n");
      out.write("									<div class=\"reg_content radio_area\">\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"smsyes_lbl\" name=\"smsyesno\" checked><label for=\"smsyes_lbl\">허용</label>\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"smsno_lbl\" name=\"smsyesno\"><label for=\"smsno_lbl\">거부</label>\r\n");
      out.write("										<p class=\"info_line\">(고객님의 편의를 위해 알림, 공지사항, 이벤트 등의 내용을 제공하고자 합니다.)</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">이메일</span>\r\n");
      out.write("									<div class=\"reg_content\">hong2018@naver.com</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"clear\">\r\n");
      out.write("									<span class=\"tit_lbl\">이메일 수신동의</span>\r\n");
      out.write("									<div class=\"reg_content radio_area\">\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"emailyes_lbl\" name=\"emailyesno\" checked><label for=\"emailyes_lbl\">허용</label>\r\n");
      out.write("										<input type=\"radio\" class=\"css-radio\" id=\"emailno_lbl\" name=\"emailyesno\"><label for=\"emailno_lbl\">거부</label>\r\n");
      out.write("										<p class=\"info_line\">(고객님의 편의를 위해 알림, 공지사항, 이벤트 등의 내용을 제공하고자 합니다.)</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<p class=\"btn_line\"><a href=\"#\" class=\"btn_baseColor\">등록</a></p>	\r\n");
      out.write("						</fieldset>\r\n");
      out.write("					</form>\r\n");
      out.write("					<!-- //appForm -->\r\n");
      out.write("				</dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("			<!-- //myinfo -->			\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //bodytext_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //container -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
