/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-25 02:52:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.trip;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<!-- location_area -->\r\n");
      out.write("		<div class=\"location_area customer\">\r\n");
      out.write("			<div class=\"box_inner\">\r\n");
      out.write("				<h2 class=\"tit_page\">TOURIST <span class=\"in\">in</span> TOUR</h2>\r\n");
      out.write("				<p class=\"location\">고객센터 <span class=\"path\">/</span> 공지사항</p>\r\n");
      out.write("				<ul class=\"page_menu clear\">\r\n");
      out.write("					<li><a href=\"#\" class=\"on\">공지사항</a></li>\r\n");
      out.write("					<li><a href=\"#\">문의하기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- //location_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- bodytext_area -->\r\n");
      out.write("		<div class=\"bodytext_area box_inner\">\r\n");
      out.write("			<form action=\"#\" class=\"minisrch_form\">\r\n");
      out.write("				\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<select name=\"###\" style=\"height: 35px;\">\r\n");
      out.write("						<option value=\"#\">제목</option>\r\n");
      out.write("						<option value=\"#\">내용</option>\r\n");
      out.write("						<option value=\"#\">작성자</option>\r\n");
      out.write("						<option value=\"#\">제목+내용</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<legend>검색</legend>\r\n");
      out.write("					<input type=\"text\" class=\"tbox\" title=\"검색어를 입력해주세요\" placeholder=\"검색어를 입력해주세요\">\r\n");
      out.write("					<a href=\"javascript:;\" class=\"btn_srch\">검색</a>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("			<table class=\"bbsListTbl\" summary=\"번호,제목,조회수,작성일 등을 제공하는 표\">\r\n");
      out.write("				<caption class=\"hdd\">공지사항  목록</caption>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"col\">번호</th>\r\n");
      out.write("						<th scope=\"col\">제목</th>\r\n");
      out.write("						<th scope=\"col\">조회수</th>\r\n");
      out.write("						<th scope=\"col\">작성일</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>1</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">이번 여름 휴가 제주 갈까? 미션 투어 (여행경비 50만원 지원)</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>2</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">박물관 미션 투어 응모 당첨자 발표</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>3</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">추석 연휴 티켓/투어 배송 및 직접 수령 안내</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>4</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">하롱베이 서비스 OPEN! (여행정보, 가이드북, 가이드맵)</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>5</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">투어리스트인투어 서비스 점검 안내 - 투어리스트인투어에서 매월 실시하는 정기점검 안내</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>6</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">이번 여름 휴가 제주 갈까? 미션 투어 (여행경비 50만원 지원)</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>7</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">박물관 미션 투어 응모 당첨자 발표</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>8</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">추석 연휴 티켓/투어 배송 및 직접 수령 안내</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>9</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">하롱베이 서비스 OPEN! (여행정보, 가이드북, 가이드맵)</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>10</td>\r\n");
      out.write("						<td class=\"tit_notice\"><a href=\"javascript:;\">투어리스트인투어 서비스 점검 안내</a> </td>\r\n");
      out.write("						<td>123</td>\r\n");
      out.write("						<td>2018-08-01</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<!-- pagination -->\r\n");
      out.write("			<div class=\"pagination\">\r\n");
      out.write("				<a href=\"javascript:;\" class=\"firstpage  pbtn\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/btn_firstpage.png\" alt=\"첫 페이지로 이동\"></a>\r\n");
      out.write("				<a href=\"javascript:;\" class=\"prevpage  pbtn\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/btn_prevpage.png\" alt=\"이전 페이지로 이동\"></a>\r\n");
      out.write("				<a href=\"javascript:;\"><span class=\"pagenum currentpage\">1</span></a>\r\n");
      out.write("				<a href=\"javascript:;\"><span class=\"pagenum\">2</span></a>\r\n");
      out.write("				<a href=\"javascript:;\"><span class=\"pagenum\">3</span></a>\r\n");
      out.write("				<a href=\"javascript:;\"><span class=\"pagenum\">4</span></a>\r\n");
      out.write("				<a href=\"javascript:;\"><span class=\"pagenum\">5</span></a>\r\n");
      out.write("				<a href=\"javascript:;\" class=\"nextpage  pbtn\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/btn_nextpage.png\" alt=\"다음 페이지로 이동\"></a>\r\n");
      out.write("				<a href=\"javascript:;\" class=\"lastpage  pbtn\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/btn_lastpage.png\" alt=\"마지막 페이지로 이동\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //pagination -->\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //bodytext_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
