/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-25 02:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.trip;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/trip/../../tiles/header.jsp", Long.valueOf(1690253112239L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<header id=\"header\">\r\n");
      out.write("		<div class=\"header_area box_inner clear\">	\r\n");
      out.write("			<h1><a href=\"javascript:;\">Tourist in tour</a></h1>\r\n");
      out.write("			<p class=\"openMOgnb\"><a href=\"#\"><b class=\"hdd\">메뉴열기</b> <span></span><span></span><span></span></a></p>\r\n");
      out.write("			<!-- header_cont -->\r\n");
      out.write("			<div class=\"header_cont\">\r\n");
      out.write("				<ul class=\"util clear\">\r\n");
      out.write("					<li><a href=\"javascript:;\">로그인</a></li>\r\n");
      out.write("					<li><a href=\"javascript:;\">회원가입</a></li>\r\n");
      out.write("				</ul>	\r\n");
      out.write("				<nav>\r\n");
      out.write("				<ul class=\"gnb clear\">\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll1\">여행정보</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_1\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">국내</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">해외</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll2\">고객센터</a>\r\n");
      out.write("				        <div class=\"gnb_depth gnb_depth2_2\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">문의하기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll3\">상품투어</a>\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_3\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">프로그램 소개</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">여행자료</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll4\">티켓/가이드</a>\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_4\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">항공</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">호텔</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("				<p class=\"closePop\"><a href=\"javascript:;\">닫기</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //header_cont -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("		<!-- location_area -->\r\n");
      out.write("		<div class=\"location_area customer\">\r\n");
      out.write("			<div class=\"box_inner\">\r\n");
      out.write("				<h2 class=\"tit_page\">TOURIST <span class=\"in\">in</span> TOUR</h2>\r\n");
      out.write("				<p class=\"location\">고객센터 <span class=\"path\">/</span> 공지사항</p>\r\n");
      out.write("				<ul class=\"page_menu clear\">\r\n");
      out.write("					<li><a href=\"#\" class=\"on\">공지사항</a></li>\r\n");
      out.write("					<li><a href=\"#\">문의하기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- //location_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- bodytext_area -->\r\n");
      out.write("		<div class=\"bodytext_area box_inner\">			\r\n");
      out.write("			<ul class=\"bbsview_list\">\r\n");
      out.write("				<li class=\"bbs_title\">박물관 미션 투어 응모 당첨자 발표</li>\r\n");
      out.write("				<li class=\"bbs_hit\">작성일 : <span>2018.08.09</span></li>\r\n");
      out.write("				<li class=\"bbs_date\">작성자 : <span>홍길자</span></li>\r\n");
      out.write("				<li class=\"bbs_content\">\r\n");
      out.write("					<div class=\"editer_content\">\r\n");
      out.write("					    안녕하세요. 믿을 수 있는 여행정보, 투어리스트인투어입니다.<br>\r\n");
      out.write("                        박물관 미션투어에 관심과 참여 감사드립니다. <br>\r\n");
      out.write("                        선정되신 분들도 진심으로 축하드립니다. <br>\r\n");
      out.write("                        앞으로도 큰 관심 부탁드리며, 메일로도 안내 예정이니 참고하시기 바랍니다. <br>\r\n");
      out.write("                        감사합니다. <br><br>\r\n");
      out.write("                        [당첨자]<br>\r\n");
      out.write("                        김용* kimyong***@naver.com <br>\r\n");
      out.write("                        인봉* in2018a***@naver.com<br>\r\n");
      out.write("                        예경* yyhong***@naver.com<br>\r\n");
      out.write("                        한진* haha***@naver.com<br>\r\n");
      out.write("                        박수* pky**@naver.com<br>\r\n");
      out.write("                        명진* mma5**@nate.com<br>\r\n");
      out.write("                        김영* rtfg6*@naver.com<br>\r\n");
      out.write("                        서영* seo20**@gmail.com<br>\r\n");
      out.write("                        윤소* yoon2***@naver.com<br>\r\n");
      out.write("                        지은* ji***@daum.net\r\n");
      out.write("                    </div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<p class=\"btn_line txt_right\">\r\n");
      out.write("				<a href=\"javascript:;\" class=\"btn_bbs\">글수정</a>\r\n");
      out.write("				<a href=\"javascript:;\" class=\"btn_bbs\">글삭제</a>\r\n");
      out.write("				<a href=\"javascript:;\" class=\"btn_bbs\">목록</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<ul class=\"near_list mt20\">\r\n");
      out.write("				<li><h4 class=\"prev\">다음글</h4><a href=\"javascript:;\">추석 연휴 티켓/투어 배송 및 직접 수령 안내</a></li>		\r\n");
      out.write("				<li><h4 class=\"next\">이전글</h4><a href=\"javascript:;\">이번 여름 휴가 제주 갈까? 미션 투어 (여행경비 50만원 지원)</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //bodytext_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("	<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
